

GET http://localhost:4000/questions

###
GET http://localhost:4000/questions/91d5074a-3892-4875-b48e-4c6cafd3380d
token:
###
POST http://localhost:4000/questions
Content-Type: application/json

{
    "title": "Javascript",
    "description": "What is the difference between Class and Object"
}

###
PUT http://localhost:4000/questions/6403ce30-465c-44d1-9065-b06cb75dcd45
Content-Type: application/json
token:
 
}

###
DELETE http://localhost:4000/questions/91d5074a-3892-4875-b48e-4c6cafd3380d
token:

###
POST http://localhost:8080/user/signup
Content-Type: application/json

{
    "firstname": "Mark",
    "lastname": "Too",
    "username":"cheboi",
    "email":"marktoo@gmail.com",
    "password":"12345678"
}


###
POST http://localhost:8080/user/login
Content-Type: application/json

{
   "email":"marktoo@gmail.com",
   "password":"12345678"
}

###
POST http://localhost:4000/user/login
Content-Type: application/json

{
  
}



###

GET http://localhost:4000/user/home
token:

###
GET http://localhost:4000/user/home
token: