CREATE TABLE votesTable (
  id VARCHAR(50) PRIMARY KEY NOT NULL,
  answer_id VARCHAR(50) FOREIGN KEY REFERENCES answerTable(id),
  user_id VARCHAR(50) FOREIGN KEY REFERENCES UsersTable(id),
  votes INT DEFAULT 0,
);